# Generated by Django 3.1.5 on 2021-01-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210107_1718'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Order',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller_profit',
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sellershop'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to='accounts.sellershop'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to='accounts.customer'),
        ),
    ]
