# Generated by Django 3.1.5 on 2021-01-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_jumgacommision_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='delivery_fee',
        ),
    ]
