# Generated by Django 3.1.5 on 2021-01-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_transaction_delivery_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='shop',
        ),
    ]
