# Generated by Django 3.1.5 on 2021-01-14 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210113_1602'),
        ('payments', '0005_auto_20210113_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchcommission',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatchcommission',
            name='type',
            field=models.CharField(choices=[('purchase', 'purchase'), ('dispatch', 'dispatch')], default='dispatch', max_length=20),
        ),
        migrations.AddField(
            model_name='jumgacommision',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='charge_type',
            field=models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], default='debit', max_length=10),
        ),
        migrations.CreateModel(
            name='SellerCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amoount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('type', models.CharField(choices=[('purchase', 'purchase'), ('dispatch', 'dispatch')], default='purchase', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order')),
            ],
        ),
    ]
