# Generated by Django 3.1.5 on 2021-01-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sellershop_subaccount_id'),
        ('orders', '0006_auto_20210115_2018'),
        ('payments', '0006_auto_20210114_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellercommission',
            old_name='amoount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='dispatchcommission',
            name='order',
        ),
        migrations.RemoveField(
            model_name='jumgacommision',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sellercommission',
            name='order',
        ),
        migrations.AddField(
            model_name='dispatchcommission',
            name='orderline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orderline'),
        ),
        migrations.AddField(
            model_name='jumgacommision',
            name='orderline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orderline'),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='orderline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orderline'),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sellershop'),
        ),
    ]
