# Generated by Django 3.1.5 on 2021-01-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20210115_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchcommission',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='jumgacommission',
            name='transaction',
        ),
    ]
