# Generated by Django 3.1.5 on 2021-01-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_transaction_initiated_by_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
    ]
