# Generated by Django 3.1.5 on 2021-01-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchcommission',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jumgacommission',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sellercommission',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
