# Generated by Django 3.1.5 on 2021-01-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210107_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellershop',
            name='subaccount_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
