# Generated by Django 3.1.5 on 2021-01-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sellershop_subaccount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellershop',
            name='account_bank',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='sellershop',
            name='account_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='sellershop',
            name='country',
            field=models.CharField(default='NG', max_length=3),
        ),
        migrations.AddField(
            model_name='sellershop',
            name='split_value',
            field=models.FloatField(default=0.5),
        ),
    ]
