# Generated by Django 3.1.5 on 2021-01-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210118_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellershop',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
