# Generated by Django 3.1.5 on 2021-01-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sellershop_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellershop',
            name='paid_reg_fee',
            field=models.BooleanField(default=False),
        ),
    ]
