# Generated by Django 3.1.5 on 2021-01-19 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sellershop_paid_reg_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=48)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('subaccount_id', models.CharField(blank=True, max_length=50, null=True)),
                ('account_bank', models.CharField(blank=True, max_length=5, null=True)),
                ('account_number', models.CharField(blank=True, max_length=12, null=True)),
                ('country', models.CharField(default='NG', max_length=3)),
                ('split_value', models.FloatField(default=0.5)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.dispatcher'),
        ),
    ]
