# Generated by Django 3.1.5 on 2021-01-19 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210119_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='dispatcher',
        ),
        migrations.AddField(
            model_name='sellershop',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.dispatcher'),
        ),
    ]
