# Generated by Django 3.1.5 on 2021-01-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_basketline_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_address2',
            new_name='billing_state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address2',
            new_name='shipping_state',
        ),
    ]
