# Generated by Django 3.1.5 on 2021-01-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210115_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketline',
            name='delivery_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketline',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='delivery_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
