# Generated by Django 3.1.4 on 2021-01-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210107_1718'),
        ('main', '0002_remove_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_shop', to='accounts.sellershop'),
        ),
    ]
