# Generated by Django 3.1.5 on 2021-01-14 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sellershop_subaccount_id'),
        ('main', '0004_auto_20210107_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.sellershop'),
        ),
    ]
