# Generated by Django 3.1.5 on 2021-01-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210114_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='helpful',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productreview',
            name='title',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
