# Generated by Django 3.1.5 on 2021-01-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210117_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ratingNumbers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
