# Generated by Django 3.1.5 on 2021-01-17 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_remove_productreview_helpful'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='helpful',
            field=models.ManyToManyField(blank=True, related_name='helpful', to=settings.AUTH_USER_MODEL),
        ),
    ]
