# Generated by Django 3.1.5 on 2021-01-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_productreview_helpful'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GBP', models.FloatField(blank=True, null=True)),
                ('KES', models.FloatField(blank=True, null=True)),
                ('GHS', models.FloatField(blank=True, null=True)),
                ('NGN', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
