# Generated by Django 3.1.5 on 2021-01-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='USD',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
