# Generated by Django 3.1.5 on 2021-01-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
